language: python

branches:
  only:
    # This is where pull requests from "bors r+" are built.
    - staging
    # This is where pull requests from "bors try" are built.
    - trying
    # Build master too
    - master

python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - if [ $TRAVIS_PYTHON_VERSION == '3.2' ]; then pip install coverage==3.7.1; else pip install coverage; fi
  - pip install coveralls

script:
  - python -bb -m coverage run -p --source=pyvisa-sim --omit="*test*" setup.py test
  - coverage combine
  - coverage report -m

after_script:
  - coveralls --verbose
